name: "Make release zip"
description: "Create a zip file for a release"
inputs:
  in-files:  # id of input
    description: |
      Files to include in the zip, Example input: 'fbl.exe', 'fbl.pdb', 'crsqlite.dll', 'crsqlite.pdb'
    required: true
  out-name:
    description: Name of the output zip file
    required: true
  github-token:
    required: true
  pre-release:
    description: "Is this a pre-release?"
    required: false
    default: false
  zip-root:
    description: "Zip root path to look for files"
    required: false
    default: "formabble/build"
runs:
  using: "composite"
  steps:
    - name: Zip Artifacts
      shell: pwsh
      run: |
        $files = ${{ inputs.in-files }}
        $path = '${{ inputs.zip-root }}'
        $existingFiles = @()
        foreach ($file in $files) {
          $fullPath = Join-Path -Path $path -ChildPath $file
          if (Test-Path $fullPath) {
            $existingFiles += $fullPath
          }
        }
        if ($existingFiles.Count -gt 0) {
          Compress-Archive -Path $existingFiles -DestinationPath ${{ inputs.out-name }}.zip -Force
          Expand-Archive -Path ${{ inputs.out-name }}.zip -DestinationPath ${{ inputs.out-name }}-extracted
        } else {
          Write-Host "No files found to zip."
        }

    - name: Upload artifacts Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.out-name }}
        path: ${{ inputs.out-name }}-extracted/*
        if-no-files-found: error

    - name: Publish release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ inputs.out-name }}.zip
        token: ${{ inputs.github-token }}
        prerelease: ${{ env.IS_PRE_RELEASE }}
