#!/bin/bash
set -e
SHARDS=${SHARDS:-../shards/build/clang-x86_64-pc-windows-msvc/reldebinfo/shards}
SHARDS_PATH=${SHARDS_PATH:-../shards}
FBL_PATH=${FBL_PATH:-../fbl}
mkdir -p build_sho
$SHARDS build -I${SHARDS_PATH}/lib ${FBL_PATH}/app/scripts/start.shs -o build_sho/start.sho
$SHARDS build -I${SHARDS_PATH}/lib ${FBL_PATH}/app/scripts/domain.shs -o build_sho/domain.sho
$SHARDS build -I${SHARDS_PATH}/lib ${FBL_PATH}/app/scripts/shared.shs -o build_sho/shared.sho
cp ${SHARDS_PATH}/shards/core/shccstrings.hpp build_sho/shccstrings.hpp
